name: Azure Publish

on:
  push:
    branches:
    - "**"
  workflow_dispatch:

jobs:
  publish-app:
    name: Publish App
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Get Id Token
        id: get-id-token
        uses: actions/github-script@v8
        with:
           script: return await core.getIDToken()
           result-encoding: string

      - name: Deploy App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_TOKEN }}
          action: upload
          app_location: ./Bot-CealingCat-Client
          api_location: ./Bot-CealingCat-Server
          output_location: dist
          github_id_token: ${{ steps.get-id-token.outputs.result }}